appURL=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
user=user
password=admin123
pwd=admin@123
fname=ABC
mname=ABC
lname=ABC
empID=1234
otherId=12345
nationality = India
DLiscNo=EBHPA66100
